# Enable performance profiling
# zmodload zsh/zprof


# This should disable '#' being interpreted as a special character
unsetopt EXTENDED_GLOB
disable -p '#'


###
# POWERLEVEL9K customizations
###
# Enables proper glyph/icon fonts in powerlevel9k
POWERLEVEL9K_MODE='nerdfont-complete'

# not currently being used, but necessary to display the right user context in my prompt
export DEFAULT_USER=$USER

# General
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status)

# SEGMENT COLORS
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='119'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='051'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='197'

# DIR COLORS
POWERLEVEL9K_DIR_HOME_BACKGROUND='249' # 075
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='249'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='249'
POWERLEVEL9K_DIR_ETC_BACKGROUND='249'


# GIT SEGMENTS
POWERLEVEL9K_VCS_GIT_HOOKS=(vcs-detect-changes git-untracked git-aheadbehind git-stash git-remotebranch git-tagname)

# GIT ICONS
POWERLEVEL9K_HIDE_BRANCH_ICON=true
POWERLEVEL9K_VCS_GIT_GITHUB_ICON=''
POWERLEVEL9K_VCS_UNSTAGED_ICON=''
POWERLEVEL9K_VCS_STAGED_ICON=''
POWERLEVEL9K_VCS_UNTRACKED_ICON=''

# PATH
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2

# PATH ICONS
POWERLEVEL9K_HOME_ICON=''
POWERLEVEL9K_HOME_SUB_ICON=''
POWERLEVEL9K_FOLDER_ICON=''
POWERLEVEL9K_ETC_ICON=''





###
# This file is sourced by interactive shells. It should define aliases,
# functions, shell options, and key bindings.
###

###
# Don't touch this. Source Prezto.
###
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

########## Customizations Below Here ##################


###
# Enable auto-completion for aliases
###
setopt completealiases

###
# Keyboard shortcuts
###

bindkey \^U backward-kill-line # Mimic bash's CTRL + U functionality


###
# Prezto configuration
###

unsetopt correct # Disable command corrections
unalias rm # Disable confirm for rm

###
# Autojump
# Install: `brew install autojump`
# https://github.com/wting/autojump
###
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh


###
# Kill whatever app is using port X
###
# alias killport="kill -9 $(listening | grep $1 | awk '{print $2}')"


###
# Kills the process listening on the port passed
# eg. killport 3333
###
killport() {
  port="$1"
  pid="$(lsof -P -n -iTCP -sTCP:LISTEN | grep $port | awk '{print $2}')"

  if [ "$pid" != "" ]; then
    kill -9 $pid
    # echo "Killed process ${pid} on port ${port}"
  else
    echo "Nothing to kill on port ${port}"
  fi
}

###
# The fuck
###
eval $(thefuck --alias)



###
# Aliases and methods
###


alias ls='lsd' # Try new "cool" ls command

alias undo-last-commit="git reset --soft HEAD~1"

# Sublime
alias s='open -a "Sublime Text"'

# Block and unblock reddit
alias play="sudo workplay play"
alias work="sudo workplay work"

# Misc
alias c="clear"
alias listening="lsof -P -n -iTCP -sTCP:LISTEN"

# Enable aliases to be sudo’ed
# alias sudo='sudo '

# Git
alias gs="git status"

# Fancy git log
alias glg="git log --graph --abbrev-commit --decorate --format=format:'%C(bold red)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all"

# Git add no whitespace
alias gaddnw="git diff -U0 -w --no-color | git apply --cached --ignore-whitespace --unidiff-zero -"

unalias gt
alias gti="git" # Typos
alias gt="git" # Typos
alias g="git"

alias ga="git add . && git commit -a -m"

unalias gco
alias gco="git checkout"

alias gsu="git submodule update --init --recursive"

alias gp="git pull"

unalias gd
alias gd="git diff -w"

alias gb="git branch"

# Rails
alias r="rails"
alias h="heroku"

# Node
alias y="yarn"




###
# rbenv (better than RVM)
###
eval "$(rbenv init -)"


###
# NVM - MOVED TO .zshenv to fix sublimelinter tslint
##
# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm





# zprof